### PR TITLE
switch to modern setuptools build and remove attrs and six deṕendencies

### PR DESCRIPTION
**Pull request by devkral**
# State

- tests work
- documentation is adjusted
- dependency less

# Extras
codestyle and docstyle were modernized on the fly

### CODE REVIEW

**Comment by glyph** [comment]
Hi Alexander!

Thanks so much for taking the time to contribute to automat. Would you mind splitting this up into several smaller, more focused PRs, though?  It's a bit hard to read through all these diffs, especially since this appears to be combining totally unrelated changes like "switching to `pyproject.toml`" and "reformatting the documentation to a different style", which appears to have introduced some small errors like removing the second space after full stops. It would be good to separate these reviews and land the easy wins quickly.

**Comment by devkral** [comment]
when I find time I can do this. But as said it should be ok because I did not do this per hand and the autoformatter should be a bit conservative.

What is the modern build environment you prefer? I can port it also to pdm, poetry whatever

**Comment by glyph** [comment]
> when I find time I can do this. But as said it should be ok because I did not do this per hand and the autoformatter should be a bit conservative.

I don't understand why the autoformatter is doing things like totally reordering classes within a file? How are you auto-formatting?

> What is the modern build environment you prefer? I can port it also to pdm, poetry whatever

I tend to prefer `pip-tools`, but mostly I would just like the contributions to be doing one thing each so they can be independently considered.

**Comment by glyph** [comment]
I do appreciate you putting the time into Automat but for the reasons described above I can't accept this as-is.  Please feel free to reopen, especially now that smaller chunks like dependency  reductions have been integrated.

**Pull request closed without merging**
