### PR TITLE
extend setup.py metadata and introduce setuptools_scm

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by glyph** [comment]
@RonnyPfannschmidt I still kind of have an allergic reaction to `setup_requires` :).  What does `setuptools_scm` do?  Could you file a ticket explaining the desired goal here?

**Comment by RonnyPfannschmidt** [comment]
@glyph the basic gist is, that setuptools_scm takes scm metadata and generates the version attribute

without something like that its impossible to fully automate releasing

the goal is to enable a release process that can be powered by a travis deploy and adding tags via the github ux

**Comment by glyph** [comment]
@RonnyPfannschmidt - OK, cool. Let's give it a shot then :).

**Comment by RonnyPfannschmidt** [comment]
@glyph as next step you.might want to add a Travis deploy for pypi, easiest done with the Travis tool

**Pull request merged**
