### PR TITLE
add pycharm's .idea/ config directory to .gitignore

### PR DESCRIPTION
**Pull request by fmoor**

### CODE REVIEW

**Comment by fmoor** [comment]
I don't know how you feel about ignoring IDE specific directories...

**Comment by glyph** [comment]
Thanks for your contribution to Automat!

However, in my opinion, `.gitignore` is for files generated *by the project*, in the course of development.  .pyc, build, and dist are created by tools that this project requires the use of.  By contrast, you, personally, use IDEA.  That would make `.idea` directories a candidate for your *personal* `core.excludesfile` configuration, since presumably you use IDEA with multiple projects.

**Comment by fmoor** [comment]
Thanks for the feedback! I didn't know about `core.excludesfile`.

**Comment by glyph** [comment]
No problem! Thanks again for your contributions. Spread the knowledge :).

**Pull request closed without merging**
