### PR TITLE
consolidation of states

### PR DESCRIPTION
**Pull request by fmoor**
This is a first go at a fix for issue #70. 
Thoughts, input and constructive criticisms are very welcome. 

#### API Changes
- `MethodicalState` -> `MethodicalFlag`
- `MethodicalMachine.state(initial=False, terminal=False, serialized=None)` ->
```python
MethodicalMachine.flag(
    states: List[Hashable], 
    initial: Hashable, 
    serialized: Optional[str] = None,
)
```
- `MethodicalState.upon(input, enter, outputs, collector=list)` -> 
```python
  MethodicalMachine.transition(
      from_: Dict[str, Hashable], 
      to: Dict[str, Hashable], 
      input: MethodicalInput, 
      outputs: List[MethodicalOutput], 
      collector: Callable = list
  )
```

#### Notes
- The `serialized` argument only replaces the flag name when the state is serialized and not the flag value.
- I did not create any alternative to the `terminal` argument to the old `state()` method because this is already a big patch.
- `from_` does not need to have all flags. If a partial set of flags are provided, the call to `transition()` will create a transition from every state that is a super set of `from_`. The omitted flags are assumed to not change in the transition.
- `to` must have the same flags as `from_`. It might be desirable to allow `to` to be a super set of `from_` or even a subset. I haven't thought too deeply on it yet. 
- My original thought was to use `json.dumps()` to serialize the states for graphviz. However, graphviz node names can not have a `:` in them. Instead, they are serialized by `'\n'.join('{} = {}'.format(k, v) for k, v in state.items())`. This was the first thing that came to mind.

#### Thoughts
- Since the state is effectively a dict now instead of a string, there are many possible mutations that might be desirable when serializing, but which are almost certainly beyond the scope of this library. Removing `serialized` from `flag()` and letting the user manipulate the state dict in their serializer function could simplify the API.
- The `initial` argument to `flag()` could be removed and the first state in `states` used as the initial state. However, this behaviour may not be intuitive for new users.

### CODE REVIEW

**Comment by glyph** [comment]
Can you resolve the conflicts on this?

One tiny nitpick (sadly don't have time for a review): I *very* intentionally avoided the word "`transition`" (I wanted to avoid state-machine jargon and just use a verb that made sense in the context of implementation) and from/to so I wouldn't need the ugly "`from_`" wart in the API.  It's a small thing but it makes it hard for me to give it an unbiased review :)

**Comment by fmoor** [comment]
@glyph, thanks for the feedback. 

I totally agree that the `_` in `from_` is ugly. I also think that `from` and `to` are extremely clear. I haven't come up with any excellent alternatives. Some alternatives might be `enter` and `exit` or `start` and `end`. I had `starting_state` and `ending_state` in [my initial proposal](https://github.com/glyph/automat/issues/70#issuecomment-329972284). I don't think any of these are as clear as `from_` and `to`.

Having no background in state machines outside of stumbling onto this library, I personally don't find `transition` to be particularly jargony. That may not be everyone's experience.

I am very open to alternatives for any of these names.

**Comment by glyph** [comment]
@fmoor Recently I've been messing around with the state machine in https://github.com/glyph/twisted/tree/statemachine-hostnameendpoint and I think I have a better sense of why this is necessary / helpful.  If you have any time for updating this branch, I'd love to talk about how it might be applied to that state machine to make it more debuggable :)

**Comment by fmoor** [comment]
I have at least a couple hours a week I can work on this. I'll have a look at that state machine Monday or Tuesday.

**Comment by fmoor** [comment]
It seems I was overly optimistic on my availability estimate. Resolving conflicts is still on my list of things to do though!

**Comment by glyph** [comment]
@fmoor Just checking in on that availability :)

**Comment by glyph** [comment]
@fmoor - hey, any chance you're going to update this?  I think the code is sufficiently stale at this point that without a champion I'm going to close it to get it off my dashboard.

That said I invite anyone (@fmoor included) who has some spare cycles to fix the conflicts and stuff to open a new PR; this close is by no means a rejection.

**Pull request closed without merging**
